# Generated by Django 4.2.3 on 2023-08-15 00:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mfp', '0002_c_store_pub_date_restaurant_pub_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c_store',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='restroom',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='c_store',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='restroom',
            name='location_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='restroom',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
